"""transcriptions and analysis

Revision ID: 102acd09d6ff
Revises: 1b3244eeb264
Create Date: 2026-07-15 14:29:45.719901
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '102acd09d6ff'
down_revision = '1b3244eeb264'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('is_spam', sa.Boolean(), nullable=True),
    sa.Column('spam_confidence', sa.Numeric(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('category_override', sa.String(), nullable=True),
    sa.Column('is_spam_override', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_analysis_call_id'), 'call_analysis', ['call_id'], unique=True)
    op.create_index(op.f('ix_call_analysis_category'), 'call_analysis', ['category'], unique=False)
    op.create_table('transcriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=True),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('words', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcriptions_call_id'), 'transcriptions', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcriptions_call_id'), table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index(op.f('ix_call_analysis_category'), table_name='call_analysis')
    op.drop_index(op.f('ix_call_analysis_call_id'), table_name='call_analysis')
    op.drop_table('call_analysis')
    # ### end Alembic commands ###
