"""recording sid unique

Revision ID: 1b3244eeb264
Revises: 1f3cc3a706c7
Create Date: 2026-07-15 13:36:27.648991
"""
from alembic import op
import sqlalchemy as sa


revision = '1b3244eeb264'
down_revision = '1f3cc3a706c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recordings', 'provider_recording_sid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'recordings', ['provider_recording_sid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recordings', type_='unique')
    op.alter_column('recordings', 'provider_recording_sid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
