"""composite call indexes

Revision ID: 1f3cc3a706c7
Revises: 4588d32649f0
Create Date: 2026-07-15 13:22:46.321599
"""
from alembic import op
import sqlalchemy as sa


revision = '1f3cc3a706c7'
down_revision = '4588d32649f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_calls_campaign_started', 'calls', ['campaign_id', 'started_at'], unique=False)
    op.create_index('ix_calls_number_started', 'calls', ['number_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_calls_number_started', table_name='calls')
    op.drop_index('ix_calls_campaign_started', table_name='calls')
    # ### end Alembic commands ###
